# Generated by Django 5.0.6 on 2026-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("doble", "Doble"),
                            ("matrimonial", "Matrimonial"),
                            ("triple", "Triple"),
                            ("cuadruple", "Cuádruple"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField(default=1)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("size_m2", models.PositiveIntegerField(blank=True, null=True)),
                ("camas", models.CharField(blank=True, max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupada", "Ocupada"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("imagen", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "habitación",
                "verbose_name_plural": "habitaciones",
                "db_table": "habitaciones",
                "ordering": ["numero"],
            },
        ),
    ]
