spring:
  application:
    name: PachaSuite
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # 24 horas en ms
  cors:
    cors:
      allowed-origins: "https://prod-front-pachasuite.onrender.com,http://localhost:4200"
